version: '3.3'
services:
  prometheus:
    image: ${USERNAME}/prometheus:${VERS}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - front_net
      - back_net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - back_net
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  mongodb-exporter:
    image: bitnami/mongodb-exporter:0.11.2-debian-10-r56
    environment:
      MONGODB_URI: 'mongodb://post_db:27017'
    networks:
      - back_net
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.18.0
    ports:
      - 9115:9115
    networks:
      - back_net
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME}/ui:${VERS}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${VERS}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:${VERS}
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.20.0/24
