---
  service:
    internalPort: 9292
    externalPort: 9292
  
  image:
    repository: vitaliygut/ui
    tag: latest

    ingress:
      class: nginx
    
    postHost:
    postPort:
    commentHost:
    commentPort: